import random
# Data pertanyaan dan jawaban
questions = [{
    "Bagian Dari Ikan Cupang": [("sirip", 1), ("ekor", 1), ("insang", 1), ("mata", 1), ("tubuh", 1)],
    "Apa ibu kota Indonesia?": [("Jakarta", 1)],
    "Apa warna bendera Indonesia?": [("Merah", 1), ("Putih", 1)],
    "Apa ibu kota Prancis?": [("Paris", 1)],
    "Apa warna bendera Amerika Serikat?": [("Merah", 1), ("Putih", 1), ("Biru", 1)],
    "Siapa penemu lampu pijar?": [("Thomas Edison", 1)],
    "Siapa penulis Harry Potter?": [("JK Rowling", 1)],
    "Apa makanan khas Italia?": [("Pizza", 1), ("Pasta", 1), ("Lasagna", 1), ("Tiramisu", 1), ("Gelato", 1)],
    "Siapa presiden pertama Amerika Serikat?": [("George Washington", 1)],
    "Apa ibu kota Jepang?": [("Tokyo", 1)],
    "Apa warna bendera Jepang?": [("Merah Putih", 1)],
    "Apa ibu kota Australia?": [("Canberra", 1)],
    "Apa ibu kota Kanada?": [("Ottawa", 1)],
    "Siapa presiden pertama Indonesia?": [("Soekarno", 1)],
    "Siapa penemu telepon?": [("Alexander Graham Bell", 1)],
    "Apa ibu kota Rusia?": [("Moskow", 1)],
    "Apa warna bendera Rusia?": [("Putih Biru Merah", 1)],
    "Apa ibu kota Inggris?": [("London", 1)],
    "Apa warna bendera Inggris?": [("Merah Putih Biru", 1)],
    "Siapa penulis novel 'To Kill a Mockingbird'?": [("Harper Lee", 1)],
    "Apa makanan khas Jepang?": [("Sushi", 1), ("Ramen", 1), ("Tempura", 1), ("Sashimi", 1), ("Udon", 1)],
    "Animals On The Sea?": [("crab", 1), ("fish", 1), ("shark", 1), ("Sealion", 1), ("Dolphin", 1), ("Turtle", 1)],
    "Siapa nama presiden ketiga Indonesia?": [("Habibie", 1)],
    "Siapa presiden kedua Indonesia?": [("Soeharto", 1)],
    "Siapa presiden pertama Indonesia?": [("Soekarno", 1)],
    "Apa ibukota Jawa Tengah?": [("Semarang", 1)],
    "Apa Ibukota Banten?": [("serang", 1)],
    "Apa ibukota Jawa Timur?": [("Surabaya", 1)],
    "Apa ibukota Sumatera Barat??": [("Medan", 1)],
    "Apa ibukota Gorontalo?": [("gorontalo", 1)],
    "Apa ibukota Riau?": [("Pekanbaru", 1)],
    "Apa ibukota Kalimantan Timur?": [("Pontianak", 1)],
    "Apa ibukota Kalimantan Tengah?": [("Palangkaraya", 1)],
    "Apa ibukota Kalimantan Selatan?": [("Banjarmasin", 1)],
    "Apa ibukota Papua Barat?": [("Monokwari", 1)],
    "Apa ibukota Papua?": [("Jayapura", 1)],
    "Sebutkan sila pertama?": [("Ketuhanan Yang Maha Esa", 1)],
    "Sebutkan sila kedua?": [("Kemanusiaan yang adil dan beradab", 1)],
    "Sebutkan sila ketiga?": [("Persatuan Indonesia", 1)],
    "Sebutkan sila kelima?": [("Keadilan sosial bagi seluruh rakyat Indonesia", 1)],
    "Apa rumah adat Provinsi Jawa Tengah?": [("Joglo", 1)],
    "Apa Rumah Adat Provinsi Aceh?": [("Krong Bade", 1)],
    "Apa rumah adat Provinsi Sumatera Barat?": [("Gadang", 1)],
    "Apa rumah adat Provinsi Bengkulu?": [("Bubungan lima", 1)],
    "Apa rumah adat Provinsi Jambi?": [("Panggung", 1)],
    "Apa rumah adat Provinsi Kalimantan Barat?": [("Rumah Panjang", 1)],
    "Kapan Hari Kartini diperingati?": [("21 April", 1)],
    "Kapan Hari Pendidikan Nasional diperingati?": [("2 Mei", 1)],
    "Kapan Hari Kebangkitan Nasional diperingati?": [("20 Mei", 1)],
    "Kapan Hari Pendidikan Nasional diperingati?": [("2 Mei", 1)],
    "Kapan Hari Kebangkitan Nasional diperingati?": [("20 Mei", 1)],
    "Kapan Hari Lahir Pancasila diperingati?": [("1 juni", 1)],
    "Kapan Hari Kemerdekaan RI diperingati?": [("17 Agustus", 1)],
    "Kapan Hari Kesaktian Pancasila diperingati?": [("1 Oktober", 1)],
    "Kapan Hari Sumpah Pemuda diperingati?": [("28 Oktober", 1)],
    "apa alat musik tradisional Jawa Barat?": [("rebbab", 1)],
    "Dari mana alat musik tifa berasal?": [("Maluku", 1), ("Papua", 1)],
    "Dari mana alat musik gamelan berasal?": [("Flores Timur", 1)],
    "Dari mana alat musik gambus berasal?": [("Riau", 1)],
    "Dari mana alat musik kolintang berasal?": [("Minahasa", 1)],
    "Julukan Banda Aceh adalah?": [("Serambi Mekkah", 1)],
    "Julukan Bogor adalah?": [("Kota Hujan", 1)],
    "Siapa raja pertama Kerajaan Kutai?": [("Kudungga", 1)],
    "Disebut apakah Candi Prambanan?": [("Roro Jonggrang", 1)],
    "Sumpah yang diucapkan Patih Gajah Mada disebut?": [("Palapa", 1)],
    "Samudera Pasai adalah kerajaan Islam pertama, dimana lokasinya?": [("Aceh", 1)],
    "Apa nama kerajaan yang didirikan Ken Arok?": [("Singasari", 1)],
    "Dimana Kerajaan Tarumanegara terletak?": [("Jawa Barat", 1)],
    "Candi Borobudur yang terkenal didirikan untuk pertama kali pada masa kerajaan?": [("Mataram Kuno", 1)],
    "Siapa pemimpin pasukan sekutu yang memasuki Medan?": [("Jenderal AWS Mallaby", 1)],
    "Kapan agresi pertama Belanda dilakukan?": [("21 Juli", 1)],
    "Napoleon sempat diasingkan ketika masa penjajahan masih berlaku di Indonesia, apa nama pulau pengasingannya?": [("Pulau Digul", 1)],
    "VOC yang sempat berkuasa di Indonesia pada masa penjajahan Belanda merupakan singkatan dari?": [("Vereenigde Oostindische Compagnie", 1)],
    "Dimana Soekarno dan Hatta diamankan oleh Golongan Muda dari pengaruh Jepang?": [("Rengasdengklok", 1)],
    "Perjanjian Kalijati ditandatangani Belanda sebagai bukti penyerahan diri kepada Jepang, tanggal berapa peristiwa tersebut?": [("8 Maret 1942", 1)],
    "Apa alasan Jepang datang dan mulai menjajah Indonesia?": [("krisis ekonomi", 1)],
    "Sungai terpanjang di dunia adalah?": [("Nil", 1)],
    "Penemu telepon adalah?": [("Alexander Graham Bell", 1)],
    "Penemu lampu adalah?": [("Thomas Alpha Edison", 1)],
    "Siapa presiden Turki tahun 2022 ini?": [("Erdogan", 1)],
    "Dimana markas kantor PBB?": [("New York", 1)],
    "Christopher Columbus merupakan?": [("Penemu", 1)],
    "Kedaulatan legislatif Indonesia dipegang oleh?": [("DPR", 1)],
    "Siapa pemegang kekuasaan eksekutif?": [("Presiden", 1), ("Wakil Presiden", 1)],
    "Siapa pemegang kekuasaan yudikatif?": [("MA", 1), ("KY", 1), ("MK", 1)],
    "Apa singkatan dari MPR?": [("Majelis Permusyawaratan Rakyat", 1)],
    "Siapa ketua umum PDIP?": [("Megawati Soekarno Putri", 1)],
    "Siapa pemimpin RI kelima?": [("Megawati", 1)],
    "Presiden keenam Republik Indonesia?": [("SBY", 1)],
    "Presiden ketujuh Indonesia?": [("Jokowi", 1)],
    "DPD adalah singkatan dari?": [("Dewan Perwakilan Daerah", 1)],
    "WHO merupakan singkatan dari?": [("World Health Organization", 1)],
    "ASEAN yaitu singkatan dari?": [("Association of SouthEast Asian Nation", 1)],
    "IMF merupakan bentuk singkat dari?": [("International Monetary Fund", 1)],
    "WTO adalah bentuk ringkas dari?": [("World Trade Organization", 1)],
    "ADB berkuasa untuk wilayah Asia, kepanjangannya adalah?": [("Asian Development Bank", 1)],
    "Kepanjangan dari APEC": [("Asia Pacific Economic Cooperation", 1)],
    "tiga karya sastra dengan penyajian narasi atau prosa?": [("novel", 1), ("cerpen", 1), ("dongeng", 1)],
    "Majas untuk menegaskan suatu hal disebut?": [("Pleonasme", 1)],
    "Majas yang maknanya melebih-lebihkan situasi atau suatu hal disebut?": [("hiperbola", 1)],
    "Novelis pengarang Laskar Pelangi?": [("Andrea Hirata", 1)],
    "Ayat-ayat Cinta pernah diangkat juga menjadi film layar lebar, pengarangnya bernama?": [("Habiburrahman El Shirazi", 1)],
    "siapa pengarang dari Marmut Merah Jambu?": [("Raditya Dika", 1)],
    "siapakah nama pengarang lagu Indonesia Raya?": [("WR Supratman", 1)],
    "Lagu ini kerap dibawakan dengan semangat, judulnya Hari Merdeka. Siapakah pengarang lagu tersebut?": [("Mutahar", 1)],
"Memperingati peristiwa di Kota Kembang, Bandung. Pengarang Halo-halo Bandung?": [("Marzuki", 1)],
    "Untuk mengenang jasa para pahlawan, Mengheningkan Cipta kerap dinyanyikan pada pelaksanaan upacara bendera hari Senin. Siapa nama pengarangnya?": [("Prawit", 1)],
    "Selain menciptakan Indonesia Raya, WR Supratman juga menciptakan sebuah lagu memperingati emansipasi wanita Indonesia, apa judulnya?": [("Hari Kartini", 1)],
    "Negara Asia yang tidak pernah dijajah?": [("Thailand", 1)],
    "Negara ini bertetangga dengan Indonesia, bahkan memiliki rumpun bahasa yang sama, yakni Melayu. Pernah berkonflik soal kepemilikan batik, apakah negara tersebut?": [("Malaysia", 1)],
    "Negara Asia ini pernah menjajah Indonesia dan membuat Belanda menyerahkan kekuasaannya, siapakah?": [("Jepang", 1)],
    "Termasuk salah satu negara komunis, namun terletak di Asia dan menutup diri dari dunia luar, minim listrik, siapakah?": [("Korea Utara", 1)],
    "Apa saja isi seblak?": [("Kerupuk", 1), ("Mie", 1), ("Telur", 1), ("Bakso", 1), ("Sosis", 1), ("Sayur", 1)],
    "Binatang paling cerdas di dunia?": [("Simpanse", 1), ("Lumba-lumba", 1), ("Gurita", 1), ("Anjing", 1), ("Orangutan", 1)],
    "Makanan yang disajikan dengan cara ditusuk?": [("Corndog", 1), ("Odeng", 1), ("Sate", 1), ("Dango", 1)],
    "Negara pertama kali corona muncul?": [("China", 1)],
    "Alat pembuat mie?": [("Panci", 1)],
    "Makanan yang mengandung zat besi?": [("Bayam", 1), ("Brokoli", 1), ("Kacang Merah", 1), ("Daging", 1), ("Tahu", 1), ("Seafood", 1), ("Dark Chocolate", 1)],
    "Negara dengan ikon patung kepala singa yang memancurkan air?": [("Singapura", 1)],
    "Sebutkan karakter princess Disney?": [("Snow White", 1), ("Rapunzel", 1), ("Ariel", 1), ("Belle", 1), ("Jasmine", 1), ("Moana", 1), ("Aurora", 1), ("Cinderella", 1)],
    "Pulau cantik di Indonesia yang kerap disangka sebagai negara oleh turis asing?": [("Pulau Bali", 1)],
    "Tanggal berapa Singapura mendeklarasikan kemerdekaannya?": [("9 Agustus", 1)],
    "India juga pernah mengalami masa penjajahan, tanggal berapa tepatnya hari kemerdekaan India?": [("15 Agustus", 1)],
    "Malaysia dan Kirgizstan memiliki tanggal kemerdekaan yang sama, yaitu?": [("31 Agustus", 1)],
    "Kapan Pantai Gading merdeka?": [("7 Agustus", 1)],
    "Negara mana yang memiliki tanggal kemerdekaan 17 Agustus, sama seperti Indonesia?": [("Gabon", 1)],
    "Apa warna bendera negara Armenia?": [("Merah", 1), ("Biru", 1), ("Kuning", 1)],
    "Negara penghasil keju?": [("Amerika Serikat", 1), ("Prancis", 1), ("Italia", 1), ("Jerman", 1), ("Spanyol", 1), ("Belanda", 1)],
    "Warna bendera Belanda?": [("Merah", 1), ("Putih", 1), ("Biru", 1)],
    "Warna bendera Belgia?": [("Hitam", 1), ("Kuning", 1), ("Merah", 1)],
    "Apakah ibukota Amerika Serikat?": [("Washington DC", 1)],
    "Ibukota Australia sesungguhnya?": [("Canberra", 1)],
    "Nama ibukota Belgia?": [("Brussel", 1)],
    "Ibukota Britania Raya?": [("London", 1)],
    "China cukup maju dalam berbagai bidang, dimana letak ibukotanya?": [("Beijing", 1)],
    "Ibukota negara Guatemala?": [("Guatemala City", 1)],
    "Nama ibukota Hungaria?": [("Budapest", 1)],
    "Apakah ibukota Irak?": [("Baghdad", 1)],
    "Alat ukur tegangan listrik disebut?": [("Voltmeter", 1)],
    "Alat ukur tekanan udara sebuah wilayah?": [("Barometer", 1)],
    "Apa alat mengukur listrik yang sedang berjalan?": [("Amperemeter", 1)],
    "Alat untuk ukur daya listrik per jam disebut?": [("KwH Meter", 1)],
    "Pengaman yang digunakan saat berhubungan intim?": [("Kondom", 1)],
    "Kopi sachet yang paling digemari anak remaja se tanah air?": [("Good Day", 1)],
    "Alat ukur satuan panjang dengan skala terkecil 1 mm disebut?": [("Mistar", 1), ("Penggaris", 1)],
    "Rempah ini cenderung terasa pedas, namun hangat di tenggorokan. Memiliki varian warna putih serta merah, apakah itu?": [("jahe", 1)],
    "Rempah ini memiliki bau yang khas dan biasa digunakan sebagai campuran nasi tutug oncom, apakah itu?": [("kencur", 1)],
    "Bumbu dapur ini berbentuk bulat-bulat kecil, warnanya cenderung lebih terang dan lebih besar ukurannya daripada ketumbar?": [("Lada", 1), ("merica", 1)],
    "Mirip ikan, namun ukurannya begitu besar dan hanya bisa dilihat ketika ke tengah laut lepas, pemakan daging, serta cenderung buas, siapa dia?": [("hiu"), 1],
    "Termasuk hewan yang sering keluar ketika malam hari, mengaum dengan khas dan kerap diidentikkan dengan hal mistis?": [("serigala", 1)],
    "hewan ini disebut sebagai raja hutan? apa nama binatangnya..?": [("singa", 1)],
    "hewan paling mematikan di Afrika, tahukah kamu?": [("kuda nil", 1)],
    "hewan buas cukup mengancam di Afrika, siapa dia?": [("buaya", 1)],
    "buayanya social media disebut?": [("sugar daddy", 1)],
    "Terkenal dengan racun berupa bisa dengan bentuk tubuh memanjang dan bisa meliuk, siapa dia?": [("ular", 1)],
    "Terlihat lucu dan menggemaskan, namun sebenarnya hewan ini termasuk pemakan daging dan bisa memangsa, apakah itu?": [("beruang", 1)],
    "Di klub mana Lionel Messi mulai bersinar dan diakui dunia dalam waktu cukup lama?": [("barcelona", 1)],
    "Cristiano Ronaldo berasal dari klub sepak bola?": [("Manchester United", 1)],
    "Jika naungan sepak bola sedunia adalah FIFA, maka naungan sepak bola se-Indonesia adalah?": [("PSSI", 1)],
    "nama klub sepak bola Bandung yang sulit akur dengan Persija Jakarta?": [("PERSIB", 1)],
    "Nama mata uang Thailand adalah?": [("Baht", 1)],
    "Nama mata uang Korea Selatan disebut?": [("won", 1)],
    "Nama mata uang Amerika Serikat yang nilainya mempengaruhi harga dunia adalah?": [("Dollar AS", 1)],
    "Untuk negara-negara Eropa, mata uang yang berlaku disebut?": [("Euro", 1)],
    "Inggris memiliki mata uang resmi bernama?": [("Poundsterling", 1)],
    "mata uang Jepang?": [("Yen", 1)],
    "mata uang China?": [("Yuan", 1)],
    "mata uang Bahrain?": [("Dinar", 1)],
    "Mata uang Filipina?": [("Peso", 1)],
    "Mata uang Malaysia?": [("Ringgit", 1)],
    "Mata uang India?": [("Rupee", 1)],
    "berapa lama capung bertahan hidup?": [("24 jam", 1)],
    "Perusahaan teknologi terbesar di Korea yang produknya hype di Indonesia?": [("Samsung", 1)],
    "Simbol kimia perak adalah?": [("AG", 1)],
    "Macam macam golongan darah": [("A+", 1), ("B+", 1), ("AB+", 1), ("O+", 1), ("A-", 1), ("B-", 1), ("AB-", 1), ("O-", 1)],
    "Siapa yang dijuluki sebagai 'Bapak Bangsa' Indonesia?": [("Ir. Soekarno", 1)],
    "Kapan terjadinya peristiwa proklamasi kemerdekaan Indonesia?": [("17 agustus 1945", 1)],
    "Siapa nama pahlawan wanita yang gugur dalam pertempuran 5 hari di Semarang?": [("Kapten Retno Wulandari", 1)],
    "Tangga apa yang nggak bisa dinaiki?": [("tangga nada", 1)],
    "Ada berapa huruf abjad?": [("26", 1)],
    "Rumah apa yang sangat butuh pertolongan?": [("Rumah Sakit", 1)],
    "Seribu dibagi dua, jadi..?": [("sobek", 1)],
    "Apa yang dilakukan polisi di tengah jalan?": [("tidur", 1)],
    "anaknya siapa yang selalu diinjak-injak?": [("anak tangga", 1)],
    "Pedagang apa yang punya sepatu banyak?": [("Pedagang Kaki Lima", 1)],
    "Awan apa yang nggak ada di langit, nggak nurunin hujan, malah bikin orang jengkel?": [("sariawan", 1)],
    "Makan apa yang nggak buat kenyang?": [("makan hati", 1)],
    "Jam apa yang dipake dukun?": [("jampi jampi", 1)],
    "Tokoh Anime Onepiece": [("Luffy", 1), ("Shanks", 1), ("Garp", 1), ("Buggy", 1), ("Nami", 1), ("Shirohige", 1)],
    "Merk Sabun": [("Dove", 1), ("Lifebuoy", 1), ("Lux", 1)],
    "orang tidur karena...": [("mengantuk", 1), ("malas", 1), ("ketiduran", 1), ("begadang", 1), ("belum tidur", 1), ("istirahat", 1)],
    "Pemeran sinetron Angling Dharma": [("Anto Wijaya", 1)],
    "Apa saja jenis kendaraan": [("becak", 1), ("sepeda", 1), ("bentor", 1), ("motor", 1), ("helikopter", 1), ("perahu", 1)],
    "Perlengkapan Playstation": [("headset", 1), ("remote", 1), ("stick", 1), ("memory card", 1), ("meja", 1), ("kursi", 1), ("colokan", 1)],
    "cara berhenti merokok": [("mati", 1), ("sakit", 1), ("miskin", 1)],
    "berhubungan dengan musim kemarau?": [("panas", 1), ("kering", 1), ("es teh", 1)],
    "peralatan dapur?": [("wajan", 1), ("spatula", 1), ("panci", 1), ("pisau", 1), ("baskom", 1), ("piring", 1)],
    "alat untuk tidur": [("bantal", 1), ("guling", 1), ("selimut", 1)],
    "olahraga di sekolah": [("sepak bola", 1), ("bulu tangkis", 1), ("basket", 1), ("futsal", 1), ("renang", 1)],
    "dimana biasanya kita bisa melihat hantu?": [("kuburan", 1), ("tempat gelap", 1), ("tempat terbengkalai", 1), ("mimpi", 1)],
    "merk susu": [("ultramilk", 1), ("milo", 1), ("dancow", 1)],
    "Animal On The Sea ?": [("Crab", 1), ("Fish", 1), ("Shark", 1), ("Sealion", 1), ("Dolphin", 1), ("Turtle", 1)],
    "Apa Saja Keuntungan Menjadi Orang Gila ?": [("terkenal", 1), ("bebas", 1), ("riang", 1), ("ditakuti", 1), ("pusat perhatian", 1)],
    "Apa Saja Hewan Paling Mematikan ?": [("Nyamuk", 1), ("Anjing", 1), ("Ular", 1), ("Tikus", 1), ("Pacarku", 1)],
    "Apa Saja Yang Ada Didalam Pesawat ?": [("Pramugara", 1), ("Pramugari", 1), ("Kokpit", 1), ("Toilet", 1), ("Pelampung", 1), ("Penumpang", 1), ("Pilot", 1)], 
    "Apa Yang Biasanya Sering Lupa Dibawa ?": [("Uang", 1), ("Dompet", 1), ("Handphone", 1), ("Kunci", 1), ("Kacamata", 1), ("Lipstik", 1), ("STNK", 1)],
    "Apa Yang Dilakukan Orang Di Stadion Sambil Menunggu Pertandingan Dimulai ?": [("Ngobrol", 1), ("Makan", 1), ("Minum", 1), ("Pemanasan", 1), ("Tidur", 1), ("Baca Koran", 1)], 
    "Apa Yang Dilakukan Orang Bila Mengantuk ?": [("Tidur", 1), ("Menguap", 1), ("Minum Kopi", 1), ("Cuci Muka", 1)],
    "Apa Yang Larut Dalam Air ?": [("Teh", 1), ("Kopi", 1), ("Gula", 1), ("Garam", 1), ("Sirup", 1)],
    "Apa Yang Terjadi Jika Sakit Hati ?": [("Nangis", 1), ("Curhat", 1), ("Stress", 1), ("Jadi Gila", 1), ("Sedih", 1)],
    "Apa Yang Diperlukan Orang Saat Didaerah Berkabut ?": [("Lampu", 1), ("Senter", 1), ("Jaket", 1), ("Kompor", 1), ("korek Api", 1)],
    "Bahan Bakar Yang Berasal Dari Alam ?": [("Bensin", 1), ("Solar", 1), ("Batu Bara", 1), ("Minyak Tanah", 1), ("Gas LPG", 1)],
    "Barang Bekas Apa Yang Biasanya Dijual Oleh Tukang Loak Dipinggir Jalan ?": [("Sepatu", 1), ("Sandal", 1), ("Kardus", 1), ("Jaket", 1), ("Tape", 1), ("Onderdil", 1)],
    "Berapa Lama Orang Menjemur Kasur ?": [("Satu Jam", 1), ("Empat Jam", 1), ("Seharian", 1)], 
    "Batuan Mineral Yang Berharga Tinggi": [("Berlian", 1), ("Intan", 1), ("Mutiara", 1), ("Permata", 1), ("Delima", 1)],
    "Benda Yang Sering Ada Di laboratorium": [("Jas", 1), ("Alat Peraga", 1), ("Mikroskop", 1), ("Tabung Kimia", 1), ("Pipet Tetes", 1), ("Spesimen", 1), ("Handscoon", 1)],
    "Berbagai Macam Rasa Susu ?": [("Manis", 1), ("Coklat", 1), ("Kopi", 1), ("Strawberry", 1), ("Mocca", 1), ("Grape", 1), ("Nenas", 1), ("Pisang", 1)],
    "Bila Lihat Wanita Berambut Indah Pengennya": [("Membelai", 1), ("Melirik", 1), ("Kagum", 1), ("Bersiul", 1), ("Memuji", 1)],
    "Bunga Dengan Warna Merah": [("Mawar", 1), ("Kembang Sepatu", 1), ("Soka", 1), ("Jengger Ayam", 1), ("Anturium", 1)], 
    "Buah yang Berawalan Huruf P": [("Pisang", 1), ("Pear", 1), ("Pepaya", 1)],
    "Cara Efektif Membunuh Nyamuk": [("Semprot", 1), ("Lempar", 1), ("Cablek", 1), ("Injek", 1), ("Tabok", 1), ("Pites", 1), ("Gigit", 1)],
    "Cara Pengawetan sayur dan buah": [("Pengeringan", 1), ("Pengalengan", 1), ("Pengasinan", 1), ("Pemasinan", 1), ("Pelumatan", 1)],
    "Ciri Ciri Gajah ?": [("Besar", 1), ("Belalai", 1), ("Gading", 1), ("Telingan Lebar", 1), ("Kulit Tebal", 1)],
    "Imunisasi Dari Pihak Posyandu / Klinik ?": [("Polio", 1), ("Campak", 1), ("Cacar", 1), ("Bcg", 1), ("Dpt", 1), ("Demam Tipoid", 1)],
    "Jenis Anjing Terkenal ?": [("Delmation", 1), ("Buldog", 1), ("Pom", 1)],
    "Jenis Hewan Vertebrata ?": [("Reptilia", 1), ("Aves", 1), ("Amphibia", 1), ("Mamalia", 1), ("Pisces", 1)],
    "Jenis Penyakit Kulit ?": [("Panu", 1), ("Kurap", 1), ("Gatal Gatal", 1), ("Koreng", 1), ("Kadas", 1), ("Kutu Air", 1)],
    "Jenis Jenis Energi": [("Listrik", 1), ("Panas Bumi", 1), ("Gas Alam", 1), ("Tenaga Air", 1)],
    "Jenis Jenis Wiraswasta": [("Nelayan", 1), ("Bertani", 1), ("Privider", 1), ("Makelar", 1), ("Traveling", 1)],
    "Jenis Kursi ?": [("Sofa", 1), ("Kursi Santai", 1), ("Kursi Goyang", 1), ("Kursi Roda", 1), ("Kursi Plastik", 1)],
    "Jenis Makanan Atau Minuman Yang Disukai Untuk Berbuka Puasa ?": [("Kurma", 1), ("Air Putih", 1), ("Teh Hangat", 1), ("Es Kelapa Muda", 1), ("Gorengan", 1), ("Kolak", 1)],
    "Jenis Sampah": [("Organik", 1), ("Unorganik", 1), ("B3", 1)],
    "Julukan Suporter Indonesia": [("Bonek", 1), ("The Jack", 1), ("Bobotoh", 1)],
    "Kalau Cewe Liat Tikus ?": [("Lari", 1), ("Teriak", 1), ("Pingsan", 1), ("Loncat", 1), ("Kaget", 1)],
    "Kalau Kamu Dirumah Sendirian Kamu Bakal ?": [("Tidur", 1), ("Belajar", 1), ("Melukis", 1), ("Teleponan", 1), ("Dengerin Musik", 1), ("Karokean", 1)],
    "Kebiasaan Waktu Tidur": [("Mendengkur", 1), ("Menguap", 1), ("Ngiler", 1), ("Mengigau", 1)],
    "Label Musik Indonesia": [("Sony", 1), ("Aquarius", 1), ("Buletin", 1), ("Billboard", 1), ("Emi", 1)],
    "Lagu Safe Band?": [("Lupakan Aku", 1), ("Lupakan Kehangatan", 1), ("Seumur Dunia", 1)],
    "Macam Macam Hantu": [("Pocong", 1), ("Kuntilanak", 1), ("Sundel Bolong", 1), ("Kolor Ijo", 1), ("Endas Glundung", 1), ("Grandong", 1), ("Kuyang", 1), ("Tuyul", 1)],
    "Macam Macam Tepung ?": [("Kanji", 1), ("Beras", 1), ("Terigu", 1), ("Tepung Jagung", 1)], 
    "Macam Macam Pisang ?": [("Raja", 1), ("Ambon", 1), ("Sepatu", 1), ("Tanduk", 1), ("Mas", 1), ("Molen", 1)],
    "Macam Tense Inggris ?": [("Perfect Tense", 1), ("Past Tense", 1), ("Present Tense", 1), ("Future", 1)],
    "Makanan Dengan Kandungan Karbohidrat": [("Nasi", 1), ("Roti", 1), ("Kentang", 1), ("Sagu", 1), ("Jagung", 1)],
    "Mainan Apa Saja Yang Ada Di Dunia Fantasi ?": [("Halilintar", 1), ("Niagara", 1), ("Arung Jeram", 1), ("Kora Kora", 1), ("Pontang Panting", 1)],
    "Makanan Khas Sulawesi ?": [("Buras", 1), ("Kapurung", 1), ("Barongkong", 1), ("Coto Makassar", 1), ("Pisang Ijo", 1)],
    "Makanan Yang Termauk Gorengan": [("Ubi", 1), ("Tahu", 1), ("Tempe", 1), ("Pisang", 1), ("Cireng", 1), ("Bakwan", 1)],
    "Makanan Yang Ada Di Warteg ?": [("Rawon", 1), ("Soto", 1), ("Pecel", 1), ("Kari Ayam", 1), ("Sayur Lodeh", 1)],
    "Mall Mall Gede Disurabaya ?": [("Ciputra Word", 1), ("Supermall Pakuwon Indah", 1), ("Tujungan Plaza", 1), ("Galaxy Mall", 1), ("Lenmarc", 1), ("Grand City", 1)],
    "Mata Air ?": [("Sungai", 1), ("Laut", 1), ("Danau", 1), ("Air Tanah", 1), ("Samudera", 1)],
    "Mata Uang Yang Berawalan R": [("Rupiah", 1), ("Riyal", 1), ("Riel", 1), ("Rupee", 1), ("Ringgit", 1)],
    "Media Komunikasi": [("Radio", 1), ("Telepon", 1), ("Fax", 1), ("Koran", 1), ("Tv", 1), ("Internet", 1)], 
    "Merk Gel Rambut ?": [("Gatsby", 1), ("Brisk", 1), ("Clear", 1)],
    "Merk Tv ?": [("Politron", 1), ("Sony", 1), ("Panasonic", 1), ("Toshiba", 1), ("Samsung", 1), ("Sanken", 1)],
    "Merek Baterai Di Indonesia ?": [("National", 1), ("ABC", 1), ("Energizer", 1), ("Eveready", 1), ("Panasonic", 1), ("Hitachi", 1)],
    "Merk Coklat Yang Digemari": [("Siver Queen", 1), ("Toblerone", 1), ("Delfi", 1), ("Cadburry", 1)],
    "Merk Hardisk ?": [("Quantum", 1), ("Seagate", 1), ("Maxtor", 1), ("Wdc", 1), ("Mdt", 1)],
    "Merk Komputer ?": [("Toshiba", 1), ("Sony", 1), ("Fujitsu", 1), ("Ibm", 1), ("Panasonic", 1), ("Simba", 1), ("Nec", 1)],
    "Merk Mobil Terkenal": [("Honda", 1), ("Mercedez", 1), ("Ferarri", 1), ("Bmw", 1), ("Jaguar", 1)],
    "Mobil Keluaran Toyota ?": [("Harrier", 1), ("Land Cruiser", 1), ("Fortuner", 1), ("Camry", 1), ("Rush", 1)],
    "Mobil Mini ?": [("Getz", 1), ("Jazz", 1), ("A Class", 1), ("Atoz", 1), ("Swift", 1), ("Karimun", 1), ("Ceria", 1)],
    "Motor Bebek Keluaran Honda": [("Supra", 1), ("Kharisma", 1), ("Bebek", 1), ("Legenda", 1), ("Prima", 1), ("Astrea", 1)],
    "Mobil Keluaran Honda ?": [("Stream", 1), ("Civic", 1), ("Cr-v", 1), ("Jazz", 1), ("City", 1)],
    "Nama Bandara Indonesia": [("Ngurah Rai", 1), ("Soekarno Hatta", 1), ("Juanda", 1), ("Adi Sucipto", 1)],
    "Nama Gurun": [("Sahara", 1), ("Gobi", 1), ("Victoria", 1), ("Thar", 1), ("Kalahari", 1)],
    "Nama Hewan Berawalan A": [("Anjing", 1), ("Ayam", 1), ("Angsa", 1), ("Amoeba", 1)],
    "Nama Nama Burung ?": [("Kutilang", 1), ("Beo", 1), ("Cendrawasih", 1), ("Elang", 1), ("Pipit", 1), ("Gagak", 1), ("Kakatua", 1)],
    "Nama Nama Danau ?": [("Toba", 1), ("Gajah Mungkur", 1), ("Jati Luhur", 1)],
    "Nama Pengarang Novel Terkenal Didunia ?": [("Jhon Grisham", 1), ("Alfred Hitchok", 1)],
    "Nama Nama  Restoran Impor": [("Cfc", 1), ("Pizza Hut", 1), ("Texas", 1), ("Dunkin Donut", 1), ("Kfc", 1)],
    "Nama Negara Yang Punya Hak Veto Pbb Dalam Bahasa Inggris": [("China", 1), ("France", 1), ("USA", 1), ("Russia", 1), ("England", 1)], 
    "Nama Pemain Bulutangkis Indonesia": [("Susi Susanti", 1), ("Alan Budikusuma", 1), ("Djoko Suprianto", 1), ("Ricky Subagia", 1)],
    "Nama Negara Di Eropa ?": [("Inggris", 1), ("Italia", 1), ("Belanda", 1)],
    "Negara Bagian Australia": [("Sydney", 1), ("Hobart", 1), ("Adelaide", 1), ("Melbourne", 1), ("Perth", 1), ("Brisbane", 1)],
    "Negara Yang Menghasilkan Jagung": [("Amerika", 1), ("Brazil", 1), ("Indonesia", 1), ("Mexico", 1), ("Prancis", 1)],
    "Negara Di Asia Timur ?": [("Cina", 1), ("Taiwan", 1), ("Korea Utara", 1), ("Korea Selatan", 1), ("Mongolia", 1)],
    "Negara Yang Menghasilkan Jagung": [("Amerika", 1), ("Brazil", 1), ("Indonesia", 1), ("Mexico", 1), ("Perancis", 1)],
    "Olahraga Yang Berbahaya ?": [("Arung Jerang", 1), ("Tinju", 1), ("Balap Mobil", 1), ("Balap Motor", 1), ("Ski Salju", 1), ("Panjat Tebing", 1)],
    "Panglima Militer ?": [("Pandiy", 1), ("Pangdam", 1), ("Pangkostrad", 1), ("Panglima TNI", 1)],
    "Pekerjaan Di Malam Hari": [("Jaga Malam", 1), ("Belajar", 1), ("Tidur", 1), ("Nonton", 1), ("Membaca", 1)],
    "Penduduk Negara Mana Yang Biasanya Memakai Pakaian Negaranya ?": [("India", 1), ("Indonesia", 1), ("Jepang", 1), ("Arab", 1), ("Vietnam", 1)],
    "Penyanyi Seksi Keluaran Hollywood": [("Britney Spears", 1), ("Shakira", 1), ("Jennifer Lopez", 1), ("Christina Aguilera", 1), ("Madona", 1)],
    "Peralatan Dapur ?": [("Kompor", 1), ("Pisau", 1), ("Wajan", 1), ("Dandang", 1), ("Saringan", 1)],
    "Profesi Yang Memerlukan Orang Dengan Tubuh Tinggi": [("Tentara", 1), ("Peragawati", 1), ("Model", 1), ("Pramugari", 1), ("Pilot", 1), ("Pramugara", 1), ("Polisi", 1)],
    "Rokok Yang Beredar Di Indonesia": [("Gudang Garam", 1), ("Djie Sam Soe", 1), ("Surya", 1), ("Malboro", 1), ("Sampoerna", 1), ("Djarum", 1), ("Wismilak", 1)],
    "Sarjana Jurusan Non Teknik": [("Ekonomi", 1), ("Psikolog", 1), ("Hukum", 1), ("Kesenian", 1), ("Designer", 1)],
    "Sebutkan Alat Petunjuk Arah ?": [("Bayangan", 1), ("Bintang", 1), ("Matahari", 1), ("Kompas", 1)],
    "Sebutkan Lagu Linkin Park ?": [("Numb", 1), ("Faint", 1), ("Breaking The Habbit", 1), ("Somewhere I Belong", 1), ("Paper Cut", 1)],
    "Senjata Tradisional Indonesia ?": [("Kujang", 1), ("Mandau", 1), ("Keris", 1), ("Keris", 1), ("Badik", 1), ("Rudus", 1), ("Parang", 1), ("Golok", 1)],
    "Seorang Sahabat ?": [("Dapat Diajak Curhat", 1), ("Saling Berbagi", 1), ("Bukan Pasangan", 1), ("Tidak Memiliki Perasaan", 1), ("Menjaga Rahasia", 1), ("Bukan Lawan Jenis", 1)],
    "Sesuatu Yang Diangkut Dengan Truk ?": [("Perabotan", 1), ("Kayu", 1), ("Beras", 1), ("Besi", 1), ("Baja", 1)],
    "Siapakah Tokoh Terkenal Nyata / Fiksi Yang Berhubungan Dengan cinta": [("Romeo Dan Juliet", 1), ("Rama Sinta", 1), ("Arjuna", 1)], 
    "Situs Berita ?": [("Kompas", 1), ("Detik", 1), ("Okezone", 1), ("Tempo", 1)],
    "Situs download software ilegal terkenal di indo?": [("gigapurbalingga", 1), ("yasir252", 1), ("kuyhAa", 1), ("JalanTikus", 1), ("Bagas31", 1), ("Alex71", 1)],
    "Struktur Sel ?": [("Membran Sel", 1), ("Sitoplasma", 1), ("Nukleus", 1), ("Organel", 1)],
    "Sungai Terpanjang Yang Ada Di Dunia": [("Nil", 1), ("Amazon", 1), ("Mississippi", 1), ("Changjiang", 1), ("Huang He", 1)],
    "Tempat Kencan Paling Enak": [("Bioskop", 1), ("Pantai", 1), ("Warnet", 1), ("Tidak Terjawab", 1), ("Rumah", 1), ("Toilet", 1)],
    "Tempat Wisata Di Indonesia ?": [("Bali", 1), ("Danau Toba", 1), ("Malioboro", 1), ("Puncak", 1), ("Borobudur", 1), ("Ancol", 1), ("Saritem", 1)],
    "Tokoh Kartun Jepang ?": [("Doraemon", 1), ("Sichan", 1), ("Kenji", 1), ("Sailormoon", 1), ("Candy Candy", 1)],
    "Tumbuhan Penyebab Dematitis": [("Setcreasea Purpurea", 1), ("Agave Augustifolia", 1), ("Scindapsus Aureus", 1)],
    "Ukuran Kertas ?": [("A4", 1), ("Legal", 1), ("A5", 1), ("Letter", 1), ("Executive", 1)],
    "Universitas Di Palembang ?": [("Tba", 1), ("Mdp", 1), ("Tgm", 1), ("Musi", 1), ("Mononofu", 1), ("Tsuwamono", 1)], 
    "Warnet Di Yogyakarta ?": [("Hijaunet", 1), ("Hasilnet", 1), ("Nasanet", 1), ("Neptune", 1), ("Planet", 1), ("Ahanet", 1)],
     "Bagian Dari Ikan Cupang": [("sirip", 1), ("ekor", 1), ("insang", 1), ("mata", 1), ("tubuh", 1)],
    "Apa ibu kota Indonesia?": [("Jakarta", 1)],
    "Apa warna bendera Indonesia?": [("Merah Putih", 1)],
    "Apa ibu kota Sumatera Utara?": [("Medan", 1)],
    "Apa makanan khas Padang?": [("Rendang", 1)],
    "Apa alat musik tradisional Jawa Barat?": [("Angklung", 1)],
    "Apa ibu kota Jawa Barat?": [("Bandung", 1)],
    "Apa makanan khas Jawa Timur?": [("Rawon", 1)],
    "Apa ibu kota Jawa Tengah?": [("Semarang", 1)],
    "Apa warna bendera Jawa Timur?": [("Hijau Putih", 1)],
    "Siapa presiden pertama Indonesia?": [("Soekarno", 1)],
    "Apa bahasa resmi Indonesia?": [("Bahasa Indonesia", 1)],
    "Apa mata uang Indonesia?": [("Rupiah", 1)],
    "Apa nama bandara internasional di Jakarta?": [("Soekarno-Hatta", 1)],
    "Apa nama candi terkenal di Jawa Tengah?": [("Borobudur", 1)],
    "Apa nama gunung tertinggi di Jawa Barat?": [("Ciremai", 1)],
    "Apa nama laut di sebelah utara Pulau Jawa?": [("Laut Jawa", 1)],
    "Apa nama pulau terbesar di Indonesia?": [("Kalimantan", 1)],
    "Apa nama ibu kota Bali?": [("Denpasar", 1)],
    "Apa makanan khas Betawi?": [("Kerak Telor", 1)],
    "Apa nama provinsi paling timur Indonesia?": [("Papua", 1)],
    "Apa nama danau terbesar di Sumatera Utara?": [("Danau Toba", 1)],
    "Apa nama tari tradisional Bali?": [("Kecak", 1)],
    "Apa nama alat musik tradisional Aceh?": [("Serune Kalee", 1)],
    "Apa nama suku asli di Kalimantan?": [("Dayak", 1)],
    "Apa nama alat musik tradisional dari Riau?": [("Gambus", 1)],
    "Apa nama ibu kota Sulawesi Selatan?": [("Makassar", 1)],
    "Apa makanan khas Sulawesi Selatan?": [("Coto Makassar", 1)],
    "Apa nama pulau terbesar di Indonesia setelah Kalimantan?": [("Sumatera", 1)],
    "Apa nama alat musik tradisional dari Sumatera Barat?": [("Saluang", 1)],
    "Apa nama tari tradisional dari Sumatera Barat?": [("Tari Piring", 1)],
    "Apa nama ibu kota Maluku?": [("Ambon", 1)],
    "Apa nama makanan khas Maluku?": [("Papeda", 1)],
    "Apa nama alat musik tradisional dari Nusa Tenggara Timur?": [("Sasando", 1)],
    "Apa nama suku asli di Papua?": [("Dani", 1)],
    "Apa nama ibu kota Papua Barat?": [("Manokwari", 1)],
    "Apa nama makanan khas Papua?": [("Sagu", 1)],
    "Apa nama alat musik tradisional dari Sulawesi Utara?": [("Kolintang", 1)],
    "Apa nama tari tradisional dari Sulawesi Utara?": [("Maengket", 1)],
    "Apa nama ibu kota Gorontalo?": [("Gorontalo", 1)],
    "Apa nama makanan khas Gorontalo?": [("Binte Biluhuta", 1)],
    "Apa nama tari tradisional dari Kalimantan Selatan?": [("Tari Baksa Kembang", 1)],
    "Apa nama alat musik tradisional dari Kalimantan Selatan?": [("Panting", 1)],
    "Apa nama ibu kota Kalimantan Timur?": [("Samarinda", 1)],
    "Apa nama makanan khas Kalimantan Timur?": [("Ayam Cincane", 1)],
    "Apa nama alat musik tradisional dari Lampung?": [("Gambus", 1)],
    "Apa nama tari tradisional dari Lampung?": [("Tari Bedana", 1)],
    "Apa nama ibu kota Sumatera Selatan?": [("Palembang", 1)],
    "Apa nama makanan khas Sumatera Selatan?": [("Pempek", 1)],
    "Apa nama alat musik tradisional dari Kalimantan Barat?": [("Sapek", 1)],
    "Apa nama tari tradisional dari Kalimantan Barat?": [("Tari Monong", 1)],
    "Apa nama ibu kota Kalimantan Tengah?": [("Palangka Raya", 1)],
    "Apa nama makanan khas Kalimantan Tengah?": [("Juhu Singkah", 1)],
    "Apa nama alat musik tradisional dari Bengkulu?": [("Serunai", 1)],
    "Apa nama tari tradisional dari Bengkulu?": [("Tari Andun", 1)],
    "Apa nama ibu kota Jambi?": [("Jambi", 1)],
    "Apa nama makanan khas Jambi?": [("Tempoyak", 1)],
    "Apa nama alat musik tradisional dari Kepulauan Riau?": [("Gendang", 1)],
    "Apa nama tari tradisional dari Kepulauan Riau?": [("Tari Zapin", 1)],
    "Apa nama ibu kota Kepulauan Riau?": [("Tanjung Pinang", 1)],
    "Apa nama makanan khas Kepulauan Riau?": [("Otak-Otak", 1)],
    "Apa nama alat musik tradisional dari Bangka Belitung?": [("Gendang Melayu", 1)],
    "Apa nama tari tradisional dari Bangka Belitung?": [("Tari Campak", 1)],
    "Apa nama ibu kota Bangka Belitung?": [("Pangkal Pinang", 1)],
    "Apa nama makanan khas Bangka Belitung?": [("Lempah Kuning", 1)],
    "Apa nama alat musik tradisional dari Nusa Tenggara Barat?": [("Gendang Beleq", 1)],
    "Apa nama tari tradisional dari Nusa Tenggara Barat?": [("Tari Gandrung", 1)],
    "Apa nama ibu kota Nusa Tenggara Barat?": [("Mataram", 1)],
    "Apa nama makanan khas Nusa Tenggara Barat?": [("Ayam Taliwang", 1)],
    "Apa nama alat musik tradisional dari Sulawesi Tenggara?": [("Gong", 1)],
    "Apa nama tari tradisional dari Sulawesi Tenggara?": [("Tari Lulo", 1)],
    "Apa nama ibu kota Sulawesi Tenggara?": [("Kendari", 1)],
    "Apa nama makanan khas Sulawesi Tenggara?": [("Kabuto", 1)],
    "Apa nama alat musik tradisional dari Sulawesi Tengah?": [("Ganda", 1)],
    "Apa nama tari tradisional dari Sulawesi Tengah?": [("Tari Dero", 1)],
    "Apa nama ibu kota Sulawesi Tengah?": [("Palu", 1)],
    "Apa nama makanan khas Sulawesi Tengah?": [("Kaledo", 1)],
    "Apa nama alat musik tradisional dari Bali?": [("Gamelan", 1)],
    "Apa nama tari tradisional dari Bali?": [("Tari Legong", 1)],
    "Apa nama ibu kota Bali?": [("Denpasar", 1)],
    "Apa nama makanan khas Bali?": [("Babi Guling", 1)],
    "Apa nama alat musik tradisional dari Yogyakarta?": [("Gamelan", 1)],
    "Apa nama tari tradisional dari Yogyakarta?": [("Tari Serimpi", 1)],
    "Apa nama ibu kota Yogyakarta?": [("Yogyakarta", 1)],
    "Apa nama makanan khas Yogyakarta?": [("Gudeg", 1)],
    "Apa nama alat musik tradisional dari Banten?": [("Angklung Buhun", 1)],
    "Apa nama tari tradisional dari Banten?": [("Tari Cokek", 1)],
    "Apa nama ibu kota Banten?": [("Serang", 1)],
    "Apa nama makanan khas Banten?": [("Rabeg", 1)],
    "Apa nama alat musik tradisional dari Jakarta?": [("Tanjidor", 1)],
    "Apa nama tari tradisional dari Jakarta?": [("Tari Topeng", 1)],
    "Apa nama ibu kota Jakarta?": [("Jakarta", 1)],
    "Apa nama makanan khas Jakarta?": [("Kerak Telor", 1)],
    "Apa nama alat musik tradisional dari Jawa Barat?": [("Angklung", 1)],
    "Apa nama tari tradisional dari Jawa Barat?": [("Jaipong", 1)],
    "Apa nama ibu kota Jawa Barat?": [("Bandung", 1)],
    "Apa nama makanan khas Jawa Barat?": [("Sate Maranggi", 1)],
    "Apa nama alat musik tradisional dari Jawa Tengah?": [("Gamelan", 1)],
    "Apa nama tari tradisional dari Jawa Tengah?": [("Tari Gambyong", 1)],
    "Apa nama ibu kota Jawa Tengah?": [("Semarang", 1)],
    "Apa nama makanan khas Jawa Tengah?":[("Nasi Liwet", 1)],
    "Apa nama alat musik tradisional dari Jawa Timur?": [("Gamelan", 1)],
    "Apa nama tari tradisional dari Jawa Timur?": [("Tari Remo", 1)],
    "Apa nama ibu kota Jawa Timur?": [("Surabaya", 1)],
    "Apa nama makanan khas Jawa Timur?": [("Rujak Cingur", 1)],
}]

def get_random_question():
    return random.choice(questions)

def check_answer(question, user_answer):
    for i, (answer, points) in enumerate(question[1]):
        if user_answer.lower() == answer.lower():
            return i, points
    return -1, 0